name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ✅ Checkout code from TIC_TAC_TOE
      uses: actions/checkout@v3

    - name: 🛠 Install g++
      run: sudo apt update && sudo apt install -y g++

    - name: 📦 Compile the project
      run: |
        mkdir -p build
        g++ tictactoe.cpp -o build/tictactoe.out

    - name: 🧪 Run basic test (simulate a flow)
      run: |
        echo "Running program..."
        ./build/tictactoe.out <<EOF
        2
        testuser
        1234
        4
        EOF
