name: Minimal Super Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  statuses: write

jobs:
  lint-main-cpp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Super Linter ONLY on main.cpp
        uses: super-linter/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          FILES_TO_LINT: main.cpp
          ENABLE_LINTERS: CPP,CLANG_FORMAT
          DISABLE_LINTERS: ALL
