# .github/workflows/ci.yml
name: C++ CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile main.cpp with sqlite3.c
      run: g++ main.cpp sqlite3.c -o app

    - name: Run the program
      run: ./app
