name: CI - Windows Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build-and-test-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: microsoft/setup-msbuild@v2

    - name: Compile with MSVC
      shell: pwsh
      run: |
        Write-Host "Compiling with MSVC..."

        $sqliteFlags = "/DSQLITE_OMIT_LOAD_EXTENSION /DSQLITE_ENABLE_RTREE /DSQLITE_ENABLE_FTS3"
        $commonFlags = "/EHsc /std:c++11"
        $warningFlags = "/W3 /wd4996 /wd4244 /wd4267 /wd4018"

        cl $commonFlags $warningFlags $sqliteFlags /Fe:main_basic.exe main.cpp sqlite3.c
        cl $commonFlags $warningFlags $sqliteFlags /Zi /DDEBUG /Fe:main_debug.exe main.cpp sqlite3.c
        cl $commonFlags $warningFlags $sqliteFlags /O2 /DNDEBUG /Fe:main_optimized.exe main.cpp sqlite3.c

    - name: Verify executables
      shell: pwsh
      run: |
        dir main_*.exe
        if (Test-Path main_basic.exe) { Write-Host "✓ main_basic.exe exists" }
        if (Test-Path main_debug.exe) { Write-Host "✓ main_debug.exe exists" }
        if (Test-Path main_optimized.exe) { Write-Host "✓ main_optimized.exe exists" }

    - name: Test executables
      continue-on-error: true
      timeout-minutes: 2
      shell: pwsh
      run: |
        $executables = @("main_basic.exe", "main_debug.exe", "main_optimized.exe")
        foreach ($exe in $executables) {
          Write-Host "Testing $exe..."
          try {
            $p = Start-Process -FilePath ".\$exe" -Wait -PassThru -NoNewWindow
            if ($p.ExitCode -eq 0) {
              Write-Host "✓ $exe completed successfully"
            } else {
              Write-Host "✗ $exe failed with exit code $($p.ExitCode)"
            }
          } catch {
            Write-Host "⚠ $exe crashed or timed out - might be expected"
          }
        }

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-executables
        path: |
          main_basic.exe
          main_debug.exe
          main_optimized.exe
        retention-days: 7
