name: CI - Build and Test SQLite C++ Project

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # This prevents other builds from being canceled
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
          - os: windows-latest
            compiler: msvc
          - os: macos-latest
            # No compiler specified for macOS - we'll install it manually
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup build environment (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        
    - name: Setup build environment (Windows)
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          
    - name: Install compiler for macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install llvm
        echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH
        
    - name: Compile and link (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        gcc -c sqlite3.c -o sqlite3.o -pthread
        g++ -c main.cpp -o main.o -pthread
        g++ -o main main.o sqlite3.o -pthread -ldl
        
    - name: Compile and link (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        clang -c sqlite3.c -o sqlite3.o -pthread
        clang++ -c main.cpp -o main.o -pthread
        clang++ -o main main.o sqlite3.o -pthread -ldl
        
    - name: Compile and link (Windows)
      if: matrix.os == 'windows-latest'
      shell: msys2 {0}
      run: |
        gcc -c sqlite3.c -o sqlite3.o -pthread
        g++ -c main.cpp -o main.o -pthread
        g++ -o main.exe main.o sqlite3.o -pthread -ldl
        
    - name: Test executable (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        ./main
        
    - name: Test executable (Windows)
      if: matrix.os == 'windows-latest'
      shell: msys2 {0}
      run: |
        ./main.exe
        
    - name: Check if database file was created
      run: |
        if [[ -f "test.db" ]]; then
          echo "✓ Database file created successfully"
          ls -la test.db || dir test.db
        else
          echo "✗ Database file not found"
          exit 1
        fi
      shell: bash
