name: Fast Native Lint for C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install linters
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format cppcheck python3-pip
          pip install cpplint

      - name: Run clang-format (style check)
        run: |
          clang-format --dry-run --Werror main.cpp sqlite3.c sqlite3.h

      - name: Run cppcheck (static analysis)
        run: |
          cppcheck --enable=all --inconclusive --quiet main.cpp sqlite3.c

      - name: Run cpplint (Google style)
        run: |
          cpplint main.cpp sqlite3.c
