name: Super-Linter for C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  super-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Super-Linter (C++ only)
        uses: github/super-linter/slim@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false         # ✅ Only changed files (faster)
          VALIDATE_CPP: true                   # ✅ Enable cpplint
          VALIDATE_CLANG_FORMAT: true          # ✅ Enable clang-format
          VALIDATE_CPPCHECK: true              # ✅ Enable cppcheck
          DISABLE_ERRORS: false                # ⛔ Fail build on lint errors
          
          # 🔻 Disable all other linters
          VALIDATE_BASH: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_MARKDOWN: false
          VALIDATE_PYTHON: false
          VALIDATE_JSON: false
          VALIDATE_YAML: false
          VALIDATE_XML: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_ENV: false
