name: Super Linter

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main

          # ✅ Only enable needed linters
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CPP: true
          VALIDATE_CPPCHECK: true
          VALIDATE_CLANG_FORMAT: true

          # ✅ Optional: Skip sqlite3 files
          FILTER_REGEX_EXCLUDE: 'sqlite3\.(c|h)'

          # ✅ Limit to relevant file types
          CPP_FILE_EXTENSIONS: '.cpp,.hpp,.cc,.hh,.cxx,.hxx'

          # ✅ Logging preferences
          LOG_LEVEL: INFO
          CREATE_LOG_FILE: true
