name: Super Linter (Only CPP)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  statuses: write

jobs:
  cpp-lint:
    name: Run C++ Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Super Linter only on main.cpp with CPP
        uses: super-linter/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          FILES_TO_LINT: main.cpp
          ENABLE_LINTERS: CPP
          DISABLE_LINTERS: ALL
