name: Super-Linter - Style Only (No Compile)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Super-Linter for C++ Style (No Compile/Syntax)
        uses: github/super-linter/slim@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_CPP: true
          VALIDATE_CPPCHECK: true
          VALIDATE_CLANG_FORMAT: true
          VALIDATE_ALL_CODEBASE: false
